extends Object

# Enemy display strings (Roman 2026-06-07). Plain-text display NAME + codex flavor
# for every enemy, keyed by scene path. Placeholder name = the scene's stem (sans
# "enemy_"); placeholder codex = "TBD". Roman fills these in over time.
#
# [REVIEW]-prefixed name/codex = AI first-pass drafts (2026-06-19) authored in the
# voice of the hand-made entries, pending Roman's review. Strip the marker on approval.
#
# Preload-referenced, NOT a class_name (headless class-cache safety, matching factions /
# beam_emitter / lane_traffic). Usage:
#   const EnemyStrings = preload("res://scripts/strings/enemy_strings.gd")
#   EnemyStrings.display_name(scene_path)   # -> display name (derived fallback if unlisted)
#   EnemyStrings.codex_entry(scene_path)    # -> codex text ("TBD" default)

const STRINGS := {
	"res://scenes/enemies/bosses/boss.tscn": {"name": "[REVIEW] The Commander", "codex": "[REVIEW] The flagship of a sector patrol and the name the bounty board most wants crossed off. It hangs back behind a screen of summoned darts and flings a grappling tether-mine to reel careless pilots onto its guns. Cut down the escort, ride out the pull, and collect."},
	"res://scenes/enemies/bosses/boss_conductor.tscn": {"name": "[REVIEW] The Conductor", "codex": "[REVIEW] The Conductor fights from a fixed throne, flanked by two satellite drones that shadow your every sidestep. Silence the satellites and the core drops its anchor, turns a furious red, and conducts a storm of homing fire itself. The toughest hull a sector can put in front of you."},
	"res://scenes/enemies/bosses/boss_howler.tscn": {"name": "[REVIEW] The Howler", "codex": "[REVIEW] A stubby, anchored gunboat that earns its name screaming through four rehearsed attacks on a loop — aimed bursts, a turning ring of fire, sweeping cascades, and a sniper's bolt. Learn the rhythm and the Howler is all bark; miss a beat and it bites hard."},
	"res://scenes/enemies/bosses/boss_reaver.tscn": {"name": "[REVIEW] The Reaver", "codex": "[REVIEW] The lightest and fastest hull ever handed a command. The Reaver strafes in lazy arcs spitting aimed fans, then commits to telegraphed dives straight down your lane — keener to run you off the field than to trade fire. Fragile, once you pin it down."},
	"res://scenes/enemies/bosses/boss_sentinel.tscn": {"name": "[REVIEW] The Sentinel", "codex": "[REVIEW] An anchored fortress-core sheathed in a shield bubble and guarded by two beam-projecting pylons. Nothing reaches the core while the pylons stand — knock them down to crack the shield, then pour everything into the narrow window before its turrets find their range."},
	"res://scenes/enemies/bosses/boss_spinwright.tscn": {"name": "[REVIEW] The Spinwright", "codex": "[REVIEW] A ring-hulled construct that spins fast enough to swat aside any shot fired into it from above — you will have to work it from the side or from beneath. When the ring unfolds it sweeps tracking beams whose only safe gap chases your position across the field."},
	"res://scenes/enemies/bosses/boss_voidmaw.tscn": {"name": "[REVIEW] The Voidmaw", "codex": "[REVIEW] A stationary maw that exhales slow-drifting singularities down the field — they drag at your hull and nothing else — while raining wobbling fans of green plasma between them. A patient game of spatial chess fought in the gaps."},
	"res://scenes/enemies/core/enemy_bomb_drone.tscn": {"name": "[REVIEW] Bomb Drone", "codex": "[REVIEW] A cheap, expendable jet-drone that sweeps in along the top of the field before wheeling over and plunging straight down a lane. It carries no guns — the drone itself is the warhead."},
	"res://scenes/enemies/core/enemy_bomber.tscn": {"name": "[REVIEW] Bomber", "codex": "[REVIEW] A heavy corporate-built bomber that lumbers down the field and holds, lashing the pilots foolish enough to chase it with rear-facing tail turrets. Slow and soaking, but punishing to tailgate — flank it or whittle it from range."},
	"res://scenes/enemies/core/enemy_cruiser.tscn": {"name": "[REVIEW] Dreadnought", "codex": "[REVIEW] A capital warship that noses into the upper field and parks, bristling with a central beam turret and two flanking gun turrets that fire on their own count. Gut the turrets and the hull soon follows. A favored centerpiece of Crimson Supremacy battle lines."},
	"res://scenes/enemies/core/enemy_crystal.tscn": {"name": "[REVIEW] Prism", "codex": "[REVIEW] A crystalline drone that hangs high in the field and splits its fire into a five-way fan of glittering pellets. Lightly built for its size, but the spread leaves few safe lanes directly beneath it. Fielded in number by the Supremacy."},
	"res://scenes/enemies/core/missile_cruiser.tscn": {"name": "[REVIEW] Missile Cruiser", "codex": "[REVIEW] A hulking mortar-ship that prowls the deep background, far beyond your guns' reach. You cannot kill it — only read its telegraphs and clear the ground it marks before the missile salvos come down."},
	"res://scenes/enemies/enemy_asteroid.tscn": {"name": "Asteroid", "codex": "It's a rock found in space."},
	"res://scenes/enemies/enemy_beam_turret.tscn": {"name": "[REVIEW] Beam Turret", "codex": "[REVIEW] A heavy turret seated at a capital ship's spine. It snaps its aim onto your position, winds up, and fires a directed beam — narrower than a Beamer's lance, but it commits the instant it locks. Read the windup and clear the line."},
	"res://scenes/enemies/enemy_bomblet.tscn": {"name": "[REVIEW] VM Bomblet", "codex": "[REVIEW] A single Void Munitions bomblet, shaken loose from a cluster mine. One hit clears it, but they travel in swarms and each one bites. Don't let a wall of them crowd you into a corner."},
	"res://scenes/enemies/enemy_boss_drone.tscn": {"name": "[REVIEW] Boss Drone", "codex": "[REVIEW] A minion drone fielded by sector flagships to pad their guard. For now it is little more than a hull and a target — it holds position and waits to die."},
	"res://scenes/enemies/enemy_gun_turret.tscn": {"name": "[REVIEW] Gun Turret", "codex": "[REVIEW] A flank turret bolted to a capital hull. It tracks your position and squeezes off a slow bolt whenever it lines up — no threat alone, but a warship's broadside is the sum of these. Strip them to defang the parent."},
	"res://scenes/enemies/enemy_mine.tscn": {"name": "VM H3 Contact Mine", "codex": "Void Munitions H3 Contact Mine, the tried and true area denial tool of corpos, privateers, and every lowlife in between. Internal magnetic sensors ensure it explodes violently on contact with just about any ship in production today."},
	"res://scenes/enemies/enemy_mine_gravity.tscn": {"name": "[REVIEW] VM G7 Cluster Mine", "codex": "[REVIEW] Void Munitions G7 Cluster Mine, a drifting core wreathed in a halo of orbiting bomblets. Pick the bomblets off one at a time or gut the core and scatter the lot — either way it spends its children before it dies."},
	"res://scenes/enemies/enemy_mine_shield.tscn": {"name": "[REVIEW] VM S2 Shielded Mine", "codex": "[REVIEW] Void Munitions S2 Shielded Mine, which drifts in dormant before snapping awake and raising an absorber shield. Catch it in the half-second before it powers up, or chew through the charges the hard way."},
	"res://scenes/enemies/enemy_mine_smart.tscn": {"name": "[REVIEW] VM K9 Pursuit Mine", "codex": "[REVIEW] Void Munitions K9 Pursuit Mine, a contact mine with just enough brain to be dangerous. It drifts harmlessly until a hull strays close, then wakes and chases it down without relenting. Best dealt with from range, before it notices you."},
	"res://scenes/enemies/enemy_mine_armored.tscn": {"name": "VM HH-4 Armored Contact Mine", "codex": "Void Munitions HH-4 Contact Mine, built to make sweeping minefields harder. Internal magnetic sensors ensure it explodes violently on contact with just about any ship in production today."},
	"res://scenes/enemies/enemy_mine_tether.tscn": {"name": "[REVIEW] VM T4 Tether Mine", "codex": "[REVIEW] Void Munitions T4 Tether Mine, which lies dormant until a ship crosses its range, then lashes out a grappling beam to haul the victim into its blast radius. Sever the link by killing it, or burn out of the pull."},
	"res://scenes/enemies/enemy_shield_pylon.tscn": {"name": "[REVIEW] Shield Pylon", "codex": "[REVIEW] A shield pylon mounted on the flank of a fortress-core, projecting the barrier that keeps the core untouchable. Worthless on its own — but while it stands, nothing you do to the core will matter. Bring it down first."},
	"res://scenes/enemies/factions/corporate/enemy_bulwark.tscn": {"name": "[REVIEW] Bulwark", "codex": "[REVIEW] A wall of corporate armor that drifts implacably down the field, shrugging off fire that would gut a lesser hull. Asset-denial in ship form — UltraGalactic spares no expense holding a contested lane."},
	"res://scenes/enemies/factions/corporate/enemy_c_s_curve.tscn": {"name": "[REVIEW] CF/A-14 Sweeper", "codex": "[REVIEW] A corporate weave-fighter that wobbles down its lane lining up aimed plasma. More disciplined than the Armada's gun-hands — every shot is meant to land, not just to fill the air."},
	"res://scenes/enemies/factions/corporate/enemy_c_s_hold.tscn": {"name": "[REVIEW] Sentry", "codex": "[REVIEW] A corporate holding-gunner that eases into station and methodically picks at you with aimed fire, demanding your attention until it is dealt with. Patient, precise, and happy to wait you out."},
	"res://scenes/enemies/factions/corporate/enemy_drone_carrier.tscn": {"name": "[REVIEW] Brood Carrier", "codex": "[REVIEW] A high-end corporate carrier that parks in the upper field and disgorges hunter-drones to do its dirty work. Expensive and well-shielded, content to spend cheaper assets while it stays safely out of reach."},
	"res://scenes/enemies/factions/corporate/enemy_hunter_drone.tscn": {"name": "[REVIEW] HK Hunter", "codex": "[REVIEW] A disposable corporate hunter-killer that locks onto your hull and flies straight in to ram. No guns and no second thoughts — UltraGalactic's idea of a cost-effective warhead."},
	"res://scenes/enemies/factions/corporate/enemy_sapper.tscn": {"name": "[REVIEW] Sapper", "codex": "[REVIEW] A corporate electronic-warfare drone that roams the field draining the charge out of anything it can reach. Lightly built and easy to miss — leave it alone and it will strip a shield bare while you are busy elsewhere."},
	"res://scenes/enemies/factions/corporate/enemy_skirmisher.tscn": {"name": "[REVIEW] Skirmisher", "codex": "[REVIEW] An aggressive corporate gun-fighter that darts in and out of range, raking aimed fire from twin muzzles and leading your movement just enough to punish sitting still. Built to harry, not to hold."},
	"res://scenes/enemies/factions/privateer/enemy_dart.tscn": {"name": "[REVIEW] Dart", "codex": "[REVIEW] The first thing most pilots meet: a cheap, fast diver that simply hurls itself straight down the field. No guns, no tricks — just a hull and a heading, fielded by the Armada in disposable numbers."},
	"res://scenes/enemies/factions/privateer/enemy_gunship.tscn": {"name": "[REVIEW] Gunship", "codex": "[REVIEW] A roaming surplus gunship that thrusts in any direction, harassing with tracer bursts from its hull guns and heavier slugs from its wingtip cannons. Tough, mobile, and a steady source of pressure across a whole engagement."},
	"res://scenes/enemies/factions/privateer/enemy_interceptor.tscn": {"name": "[REVIEW] Interceptor", "codex": "[REVIEW] A fast strike fighter that dives across the field in squads, kicking a trail of drifting missiles behind each pass. Ex-military hardware the Armada bought cheap and flies hard."},
	"res://scenes/enemies/factions/privateer/enemy_minelayer.tscn": {"name": "[REVIEW] Minelayer", "codex": "[REVIEW] A lumbering converted hauler that crawls across the top of the field seeding mines in its wake. Slow and poorly armed for its size, but the field it leaves behind does the killing for it."},
	"res://scenes/enemies/factions/privateer/enemy_p_m_cannon.tscn": {"name": "[REVIEW] Spectre", "codex": "[REVIEW] A holding artillery platform that lobs slow, heavy shells straight down from alternating barrels. Easy to ignore right up until one connects — and then you won't ignore it again."},
	"res://scenes/enemies/factions/privateer/enemy_p_m_pulse.tscn": {"name": "[REVIEW] Viper", "codex": "[REVIEW] A deep-holding gunner that throws aimed, weaving bolts of plasma down at you. Cheap market plasma tech bolted to a stolen airframe — sloppy by design, but it keeps you moving."},
	"res://scenes/enemies/factions/privateer/enemy_p_s_jet.tscn": {"name": "Jet", "codex": "[REVIEW] A light, fast fighter that dives in firing from its twin nose guns. The Armada's workhorse interceptor — nothing special under the repainted hull, but there are always more of them."},
	"res://scenes/enemies/factions/privateer/enemy_p_m_wing.tscn": {"name": "Wing", "codex": "[REVIEW] A broad-winged strike craft that sweeps across the field unloading a wide spread of drifting missiles. Built to blanket an area rather than to aim — saturate the lane and let the pilot sort out the rest."},
	"res://scenes/enemies/factions/privateer/enemy_p_s_drop.tscn": {"name": "[REVIEW] Caltrop", "codex": "[REVIEW] A descender that dribbles a trail of slow-crawling munitions behind it like caltrops, clogging the lane it leaves. Harmless to chase — costly to follow."},
	"res://scenes/enemies/factions/privateer/enemy_p_s_gray.tscn": {"name": "[REVIEW] Sabre", "codex": "[REVIEW] A bare-bones diver in unpainted surplus gray, flown straight down the field by whatever crew the Armada could press into the cockpit. Unarmed and entirely expendable."},
	"res://scenes/enemies/factions/privateer/enemy_p_s_green.tscn": {"name": "[REVIEW] Hornet", "codex": "[REVIEW] A light skirmisher that weaves and slides down the field without firing a shot, trusting numbers over guns. The green decals mark another batch of cut-rate Armada fodder."},
	"res://scenes/enemies/factions/privateer/enemy_rocket.tscn": {"name": "[REVIEW] Rocket", "codex": "[REVIEW] A slow, deliberate gunship that drifts into position and unloads rocket salvos from its launch rack while raking tracers from its hull guns. Built to anchor a line and make space expensive."},
	"res://scenes/enemies/factions/supremacy/enemy_frigate.tscn": {"name": "[REVIEW] Tyrant", "codex": "[REVIEW] A slow, heavily armored warship that wheels to face you and rakes the field with a rolling broadside — a steady drumbeat of fire from whichever flank you're caught on. Built to grind down anyone who can't out-position it."},
	"res://scenes/enemies/factions/supremacy/enemy_s_m_plasma.tscn": {"name": "Scourge", "codex": "A medium gunship built with a wide-bore plasma spitter that unleashes shots of shaped plasma at victims. What they lack in speed and agility they make up for in damage potential, as the heavy shots are hard to avoid and especially effective against shields."},
	"res://scenes/enemies/factions/supremacy/enemy_s_m_push.tscn": {"name": "Overseer Frigate", "codex": "A tough frigate built with a pair of armored dome turrets firing powerful cannon shots at any ship foolish enough to get within range. Powerufl engines allow it to move swiftly, closing on prey, or maneuvering to advantageous positions with shocking speed."},
	"res://scenes/enemies/factions/supremacy/enemy_s_s_hotrod.tscn": {"name": "Lash", "codex": "A stripped-down racing frame fitted for combat, what it lacks in armor and firepower it makes up for in sheer speed and rate of fire. Crimson Supremacy outriders fly them to run prey down and herd it toward the heavier guns."},
	"res://scenes/enemies/factions/supremacy/enemy_s_s_rush.tscn": {"name": "Mauler", "codex": "An aggressive close-range brawler that charges straight in, firing short, snapping bursts from twin muzzles. It would sooner be in your face than across the field — typical of the Supremacy's contempt for caution."},
	"res://scenes/enemies/factions/zealot/enemy_beam_shooter.tscn": {"name": "Lantern", "codex": "A beam-wielding ship built as a testbed for the deadly plasma beam program the Evantians embarked upon some time ago. It is powered by numerous internal firecores and has extensive inertial damping tech and control thrusters that allow it to rake the dark with a purifying beam of fire that obliterates anything in its path."},
	"res://scenes/enemies/factions/zealot/enemy_beamer_lock.tscn": {"name": "Arbiter", "codex": "The Evantians carried out many experiments with plasma-beam technology, and the Arbiter is one result. It utilizes powerful gyroscopic mechanisms to rotate itself into firing position, then uses gravity locks to hold itself in place to fire. The plasma beam generated by this weapons platform is devastating, and best avoided."},
	"res://scenes/enemies/factions/zealot/enemy_beamer_tracker.tscn": {"name": "Inquisitor", "codex": "Agile, and accurate, these hand-built vessels are equipped with powerful beam projectors and multiple thruster arrays that allow it to quickly pivot and direct its beam of purifying plasma on its victims. It's bulk does mean it rotates slowly enough to outmaneuver, which is good, because only fools take on these vessels head-on."},
	"res://scenes/enemies/factions/zealot/enemy_burner.tscn": {"name": "Pyre", "codex": "Pyres are always dispatched in pairs, stringing a searing curtain of firecore-powered energy between them. The Evantians believe that to pass between two Pyres is to be cleansed, and these vessels rarely give victims the choice to partake in purification or now."},
	"res://scenes/enemies/factions/zealot/enemy_z_m_helix.tscn": {"name": "Helix Frigate", "codex": "The Helix-class frigate is built and flown by the Evantians primarily for its appearance, but the top-mounted plasma cannon is capable of firing precise, powerful shots if it ever needs to fight."},
	"res://scenes/enemies/factions/zealot/enemy_z_s_bloom.tscn": {"name": "Firecore Bloom", "codex": "The bloom is a semi-stationary plasma generator that creates concentric rings of plasma charges for area denial. When destroyed, the cohesion fields break down, releasing balls of plasma in all directions."},
	"res://scenes/enemies/factions/zealot/enemy_z_s_manta.tscn": {"name": "Disciple", "codex": "Slow moving and lightly armed, the Disciple is among one of the more common craft utilized by the Evantian fleets, often put to work as escorts in large numbers, their presence is meant to distract and any kills they score are a bonus."},
	"res://scenes/enemies/factions/zealot/enemy_z_s_acolyte.tscn": {"name": "Acolyte", "codex": "The Acolyte is neither fast nor particularly agile, but it does bring two wide-angle plasma dispersing guns to bear, filling the void with shots meant to hit anything caught in the way."},
	"res://scenes/enemies/factions/zealot/enemy_z_s_drifter.tscn": {"name": "Drifter", "codex": "An unarmed scout, the Drifter is rarely a danger to anyone on its own, but is always a precursor to the arrival of greater numbers of Evantian forces. The pilots are selected from the most disposable of the ranks, given little training, and often used as screening waves to protect more valuable craft."},
	"res://scenes/enemies/factions/zealot/enemy_z_s_shiv.tscn": {"name": "Shiv", "codex": "Shiv-class interceptors lack weapons of any kind, and instead rely on sharpened hulls reinforced for impact. Shivs are piloted by the elderly, prisoners, and zealots who have agreed to deliver the light of the Firecore to deserving heathen foes."},
	"res://scenes/enemies/factions/zealot/enemy_z_s_sword.tscn": {"name": "Sword Frigate", "codex": "The Sword-class Frigate is built and fielded exclusively by the Evantian Theocracy, and is a fast workhorse combat vessel. It features multiple omni-directional plasma casters capable of rapidly firing salvos at enemies."},
	"res://scenes/enemies/factions/zealot/enemy_z_s_crook.tscn": {"name": "Crook", "codex": "The Crook is a modestly fast fighter with a rapid-fire plasma cannon. What it lacks in armor and maneuverability it makes up for with rate of fire."},
	"res://scenes/enemies/factions/zealot/enemy_z_s_pilgrim.tscn": {"name": "Pilgrim", "codex": "The Pilgrim isn't fast, maneuverable, or terribly well armored, but it does feature dual heavy plasma cannons capable of firing rapidly at any foes caught in their sights."},
	"res://scenes/enemies/factions/zealot/enemy_z_s_censer.tscn": {"name": "Censer Frigate", "codex": "The Censer-class frigate is not especially fast, but it is well armored and features two nose-mounted heavy wave projectors that create walls of burning plasma."},
	"res://scenes/enemies/factions/zealot/enemy_z_s_cross.tscn": {"name": "Cross Gunship", "codex": "A fast-moving gunboat with omni-directional thrust capacity and two front-mounted laser cannons for rapid, precise attack. While speedy, these vessels are not especially resilient and tend to explode violently when destroyed."},
	"res://scenes/enemies/factions/zealot/enemy_z_s_rebuker.tscn": {"name": "Rebuker", "codex": "The Rebuker is a slow moving but maneuverable attack vessel that is heavily armed, wielding two forward facing plasma cannons. What it lacks in speed it makes up for in power and capability to harrass combatants with direct, accurate fire."},
	"res://scenes/enemies/factions/zealot/enemy_z_s_spear.tscn": {"name": "Spear Frigate", "codex": "The high-speed Spear-Class Frigate trades conventional plasma cannons for a central firecore-powered plasma generator that can fire coherent beams. It is fast, and agile, with powerful thruster engnines allowing it to quickly reverse and pivot in space to get its beam on target quickly."},
	"res://scenes/enemies/factions/zealot/boss_z_l_shepherd.tscn": {"name": "The Shepherd", "codex": "An Evantian capital-ship that herds its flock to slaughter. Its four turrets carry the fight, delivering salvos of burning plasma. It also carries massive missile bays capable of dispatching dozens of warheads in rapid succession for area denial or stand-off fleet engagement. The Shepherd is never seen alone, and any attempt to breach its hull will require a Starblaster to engage with its escorting flock first."},
	"res://scenes/enemies/factions/zealot/firecore_core.tscn": {"name": "Firecore", "codex": "The sacred heart of every Evantian hull, this unstable micro-star serves as the power source for every every system, and the point of worship for its crew. The Theocracy worships is as a source power and salvation, believing that one day all the firecores will rupture, and consume the worthy in great waves of fire and light."},
	"res://scenes/enemies/factions/zealot/firecore_hazard.tscn": {"name": "Loose Firecore", "codex": "A firecore shaken loose from a dying Evantian ship, rather than detonating it drifts through space, a micro-star burning brightly in the void"},
	"res://scenes/enemies/tether_mine.tscn": {"name": "VM-T4 Tether Mine", "codex": "Void Munitions T4 Tether Mine in its capital-launched configuration — flung into the field by flagships to pin a pilot in place. Dormant until you stray near, then it lashes out a grappling beam and reels you in. Kill it to cut the line."},
}


# Display name for a scene path. Falls back to a derived name (file stem, sans
# "enemy_", underscores -> spaces) for any scene not in the table.
static func display_name(scene_path: String) -> String:
	var e: Variant = STRINGS.get(scene_path, null)
	if e != null and str(e.get("name", "")) != "":
		return str(e["name"])
	return _derive(scene_path)


# Codex flavor text for a scene path ("TBD" default for unlisted / unfilled).
static func codex_entry(scene_path: String) -> String:
	var e: Variant = STRINGS.get(scene_path, null)
	if e != null:
		return str(e.get("codex", "TBD"))
	return "TBD"


static func _derive(scene_path: String) -> String:
	var stem: String = scene_path.get_file().get_basename()
	if stem.begins_with("enemy_"):
		stem = stem.substr(6)
	return stem.replace("_", " ")
