extends Object

# Enemy display strings (Roman 2026-06-07). Plain-text display NAME + codex flavor
# for every enemy, keyed by scene path. Placeholder name = the scene's stem (sans
# "enemy_"); placeholder codex = "TBD". Roman fills these in over time.
#
# [REVIEW]-prefixed name/codex = AI first-pass drafts (2026-06-19) authored in the
# voice of the hand-made entries, pending Roman's review. Strip the marker on approval.
#
# Preload-referenced, NOT a class_name (headless class-cache safety, matching factions /
# beam_emitter / lane_traffic). Usage:
#   const EnemyStrings = preload("res://scripts/strings/enemy_strings.gd")
#   EnemyStrings.display_name(scene_path)   # -> display name (derived fallback if unlisted)
#   EnemyStrings.codex_entry(scene_path)    # -> codex text ("TBD" default)

const STRINGS := {
	"res://scenes/enemies/bosses/boss.tscn": {"name": "[REVIEW] The Commander", "codex": "[REVIEW] The command hull of a sector patrol, and the highest bounty that patrol will ever put in the field. It fights as a coordinator before a gunship: an onboard drone-control suite scrambles a screen of KKD Darts to soak fire, while a spinal launcher — the same grappling rig Void Munitions sells as a tether-mine — reels a target in onto its guns. Built in small numbers and refit ship by ship, so no two are rigged quite alike."},
	"res://scenes/enemies/bosses/boss_conductor.tscn": {"name": "[REVIEW] The Conductor", "codex": "[REVIEW] A stationary command-and-control platform that fights through a pair of slaved satellite drones, working them as forward targeting relays while the core stays locked to its anchor. Cut the relays down and the core falls back to a mode built into every hull of its class — venting its reactor to a hard red glow and conducting its own barrage of homing fire. The heaviest command hull a sector fields, and the last of a patrol to fall."},
	"res://scenes/enemies/bosses/boss_howler.tscn": {"name": "[REVIEW] The Howler", "codex": "[REVIEW] A stubby, anchored artillery boat whose fire-control runs a fixed four-part program — aimed bursts, a rotating ring, sweeping cascades, and a single high-velocity bolt — cycled in the same order every engagement. The name comes from the turbine shriek its overworked munitions feed throws off between volleys. An old and simple design, cheap to build and cheaper to service, which is why sectors keep fielding it."},
	"res://scenes/enemies/bosses/boss_reaver.tscn": {"name": "[REVIEW] The Reaver", "codex": "[REVIEW] A light interceptor airframe pushed up to command spec — the fastest hull ever handed a patrol, and the most fragile. Its pilots favor slashing strafe-runs and long committed dives over standing fights, trusting the frame's speed to break contact before return fire can land. The armor it shed for that speed is the price: once anything pins it, it does not last."},
	"res://scenes/enemies/bosses/boss_sentinel.tscn": {"name": "[REVIEW] The Sentinel", "codex": "[REVIEW] A static fortress-core, closer to an emplacement than a ship, wrapped in a barrier fed by two external beam-pylons. Splitting the shield generator off the hull is deliberate — as long as a single pylon still projects, nothing reaches the core, and its turrets are left free to range in on whatever tries. Only with both projectors down does the core become a target at all, which makes it a siege problem more than a duel."},
	"res://scenes/enemies/bosses/boss_spinwright.tscn": {"name": "[REVIEW] The Spinwright", "codex": "[REVIEW] A ring-hulled construct built around a single trick: it spins its armored outer ring fast enough to bat aside any shot fired into it from directly above, forcing attackers onto its flanks or underside. On command the ring unfolds into a beam array and sweeps the field, its emitters phased so that only one narrow gap ever runs cold at a time. An engineering curiosity, fielded as much to prove the concept as to hold a line."},
	"res://scenes/enemies/bosses/boss_voidmaw.tscn": {"name": "[REVIEW] The Voidmaw", "codex": "[REVIEW] A stationary weapons platform built around a caged gravitic generator — its 'maw' vents slow, self-contained singularities that drag on a hull without ever damaging it, herding a target into the wobbling fans of green plasma it fires between them. The gravity tech is unstable and power-hungry, which is why it rides a hull that cannot move and rarely leaves a fixed defensive post. As much a field test of an unproven weapon as a warship."},
	"res://scenes/enemies/core/enemy_core_bomber.tscn": {"name": "B-220 Incisor", "codex": "A heavy corporate-built bomber designed for delivering stand-off munitions such as torpedos and missiles. It lacks speed and defensive armaments, but it is well armored and can carry a large volume of ordnance."},
	"res://scenes/enemies/core/enemy_core_bomber_thin.tscn": {"name": "B-49 Lancer", "codex": "A sleek, long-bodied bomber."},
	"res://scenes/enemies/core/enemy_cruiser.tscn": {"name": "[REVIEW] Dreadnought", "codex": "[REVIEW] The Crimson Supremacy's standard line-of-battle cruiser, built to anchor the center of a formation while lighter hulls maneuver off its flanks. It mounts a spinal beam turret between two independently-tracking gun batteries, each running its own fire-control so the ship keeps firing even as sections are shot away. With the turrets gone the hull is only armor — durable, but toothless."},
	"res://scenes/enemies/factions/corporate/enemy_c_m_widow.tscn": {"name": "A-110 Widow", "codex": "A medium-sized attack hull that straddles the line between fighter and bomber. What it lacks in speed it makes up for in armaments."},
	"res://scenes/enemies/factions/supremacy/enemy_s_m_missile_cruiser.tscn": {"name": "[REVIEW] Missile Cruiser", "codex": "[REVIEW] A Crimson Supremacy siege cruiser that fires from the deep field, standing off far beyond the reach of any fighter's guns. It carries no direct armament at all — only a saturation missile battery walked across marked ground in successive salvos, a doctrine the Supremacy scaled down from planetary bombardment and never fully tamed. Unreachable from the front line by design; the fighters below are meant only to clear the ground it targets."},
	"res://scenes/enemies/enemy_asteroid.tscn": {"name": "Asteroid", "codex": "It's a rock found in space."},
	"res://scenes/enemies/enemy_beam_turret.tscn": {"name": "[REVIEW] Beam Turret", "codex": "[REVIEW] A heavy directed-beam mount seated along the spine of a capital hull, the one place the reactor feed can support a sustained emitter. It slews onto a target, spends a fixed charge cycle winding up, then commits to a lance narrower than a dedicated Beamer's — traded down for a mount compact enough to bolt onto a ship never designed to carry it. One emitter among a warship's many, and seldom the one that lands the killing shot."},
	"res://scenes/enemies/enemy_bomblet.tscn": {"name": "VM-7 Bomblet", "codex": "A single Void Munitions bomblet built as a light area denial weapon, small enough for mass dispersal from patrol craft, and powerful enough to destroy small fighters without being easily detected by sensors."},
	"res://scenes/enemies/enemy_boss_drone.tscn": {"name": "[REVIEW] Boss Drone", "codex": "[REVIEW] A bare escort drone, mass-produced to pad out a flagship's guard detail. Little more than a hull, an engine, and a transponder, it holds whatever station its parent assigns it and carries no armament worth the name. A body counted in the escort tally and spent to draw fire off the command hull behind it."},
	"res://scenes/enemies/enemy_gun_turret.tscn": {"name": "[REVIEW] Gun Turret", "codex": "[REVIEW] A standard flank battery, sold as a modular unit and bolted along the broadsides of capital hulls by the dozen. Each mount tracks on its own and squeezes off a slow bolt when it bears — negligible alone, but a warship's broadside is only ever the sum of them. Stripping the batteries is the surest way to leave a capital hull toothless."},
	"res://scenes/enemies/enemy_mine.tscn": {"name": "VM H3 Contact Mine", "codex": "Void Munitions H3 Contact Mine, the tried and true area denial tool of corpos, privateers, and every lowlife in between. Internal magnetic sensors ensure it explodes violently on contact with just about any ship in production today."},
	"res://scenes/enemies/enemy_mine_gravity.tscn": {"name": "[REVIEW] VM G7 Cluster Mine", "codex": "[REVIEW] Void Munitions G7 Cluster Mine, a drifting core that holds a ring of smaller bomblets in slow magnetic orbit around itself. Struck directly, its cohesion field collapses and flings the whole clutch outward at once; chipped at from the edge, it sheds the bomblets one at a time. Either way it spends its children before the core goes — a single charge sold as many."},
	"res://scenes/enemies/enemy_mine_shield.tscn": {"name": "[REVIEW] VM S2 Shielded Mine", "codex": "[REVIEW] Void Munitions S2 Shielded Mine, a contact charge fitted with a compact absorber field adapted from corporate shield tech. It drifts inert until a hull nears, then powers the field up in a fraction of a second — struck before it wakes it dies like any other mine, but caught after, it soaks hit upon hit behind the barrier. Void Munitions markets it for one purpose: to make minesweeping expensive."},
	"res://scenes/enemies/enemy_mine_smart.tscn": {"name": "[REVIEW] VM K9 Pursuit Mine", "codex": "[REVIEW] Void Munitions K9 Pursuit Mine, a contact charge given just enough of a seeker package to hunt. It drifts dormant on standby power until a hull crosses its trip radius, then wakes a small thruster stack and runs the target down without relenting. The catalog sells the seeker as a feature; even Void Munitions' own handlers deploy them last, and from a distance."},
	"res://scenes/enemies/enemy_mine_armored.tscn": {"name": "VM HH-4 Armored Contact Mine", "codex": "Void Munitions HH-4 Contact Mine, built to make sweeping minefields harder. Internal magnetic sensors ensure it explodes violently on contact with just about any ship in production today."},
	"res://scenes/enemies/enemy_mine_tether.tscn": {"name": "[REVIEW] VM T4 Tether Mine", "codex": "[REVIEW] Void Munitions T4 Tether Mine, the field-scattered cousin of the grappling charge flagships fling by hand. It lies dormant until a hull enters range, then fires a tractor beam to haul its catch back into its own blast radius — the whole kill riding on the tether, since the charge itself never moves to close. Destroy the mine and the beam cuts out; a strong enough engine can simply overpower the pull."},
	"res://scenes/enemies/enemy_shield_pylon.tscn": {"name": "[REVIEW] Shield Pylon", "codex": "[REVIEW] An external shield projector, mounted in pairs on the flanks of a fortress-core. Splitting the generator off the hull is deliberate — the core can carry heavier armor and armament when it doesn't have to house the emitter, and the barrier holds as long as a single pylon still feeds it. Barely armed and useless as a weapon, but a fortress is only ever as protected as its last standing projector."},
	"res://scenes/enemies/factions/corporate/enemy_c_l_bulwark.tscn": {"name": "[REVIEW] Bulwark", "codex": "[REVIEW] A heavy corporate armor-hull whose whole purpose is to occupy a lane and refuse to leave it. UltraGalactic Concerns builds the Bulwark almost without weapons, spending the entire budget on plating and reactor mass so it can wade through fire that would gut a lighter ship. Fielded as a mobile blockade — and a lane held shut is, by the corporate ledger, an asset denied."},
	"res://scenes/enemies/factions/corporate/enemy_c_s_curve.tscn": {"name": "CF/A-14 Excisor", "codex": "The CF/A-14 is a split hull attack fighter made for speed and maneuverability.It lacks a main cannon of any kind and relies on stand-off munitions such as missiles and torpedoes to strike targets from afar."},
	"res://scenes/enemies/factions/corporate/enemy_c_s_hold.tscn": {"name": "[REVIEW] Sentry", "codex": "[REVIEW] A corporate holding-gunner, the posted sentry of a standard UltraGalactic security detachment. It settles into a fixed station and works a target over with slow, precise aimed fire, built for endurance and accuracy rather than speed or maneuver. Cheap enough to post in numbers and patient enough to whittle down anything that lingers in its arc."},
	"res://scenes/enemies/factions/corporate/enemy_c_l_hive.tscn": {"name": "[REVIEW] Hive", "codex": "[REVIEW] A high-end UltraGalactic carrier that anchors at the top of the field and fights entirely through its cargo — bay after bay of expendable Flechette drones launched to swarm while the carrier stays shielded and out of reach. It is among the costliest hulls the corporation fields, and its whole doctrine is to protect that investment by spending cheaper drones by the hundred in its place. The UltraGalactic ledger built into a warship."},
	"res://scenes/enemies/factions/corporate/enemy_c_s_sapper.tscn": {"name": "[REVIEW] Sapper", "codex": "[REVIEW] A corporate electronic-warfare drone built around a short-range charge-siphon in place of a gun. It roams the field draining the shield reserves out of anything it can close on, lightly built and easily overlooked while it works. UltraGalactic classes it as support equipment rather than a combatant — its damage is a shield quietly stripped bare while attention is elsewhere."},
	"res://scenes/enemies/factions/corporate/enemy_c_s_archer.tscn": {"name": "[REVIEW] Archer", "codex": "[REVIEW] A corporate line-fighter, the standard-issue interceptor of UltraGalactic security work. It carries a pair of fixed forward guns and nothing else, built to hold its range and deliver disciplined, aimed fire on a steady schedule. Unremarkable by design — cheap to build, simple to fly, and issued in whatever numbers a contract calls for."},
	"res://scenes/enemies/factions/corporate/enemy_c_s_specter.tscn": {"name": "[REVIEW] Specter", "codex": "[REVIEW] A corporate raider that trades the line-fighter's discipline for saturation, arranging four independent muzzles to wash an entire lane rather than aim at any one mark. Where UltraGalactic's cheaper hulls ration their fire, the Specter is built to flood the space ahead of it and let the spread do the work. A more expensive answer to the maneuverable targets that keep slipping the aimed guns."},
	"res://scenes/enemies/core/enemy_core_s_dart.tscn": {"name": "KKD-4 Dart", "codex": "A Kinetic Kill Drone, the 'Dart' is a fast moving drone designed to be fielded in large numbers and sent into oncoming fleets. They serve as screening forces that draw fire, distract interceptors, and punch holes in defenses before the main force arrives."},
	"res://scenes/enemies/core/enemy_core_s_flechette.tscn": {"name": "UID-54 Flechette", "codex": "A needle-thin throwaway drone that is one step shy of just being a missile. The Unmanned Interceptor Drone is a fast, has no guns, and is cheap enough that carriers seed them by the hundreds."},
	"res://scenes/enemies/factions/privateer/enemy_p_m_gunship.tscn": {"name": "[REVIEW] Gunship", "codex": "[REVIEW] A Vertarine Armada surplus gunship — an ex-military patrol hull kept flying long past its service life. Omni-directional thrusters let it slide in any heading while it harries with tracer fire from its hull guns and heavier slugs from a pair of wingtip cannons. Tough, endlessly mobile, and cheap for the Armada to keep aloft; the kind of hull they run until it comes apart."},
	"res://scenes/enemies/factions/privateer/enemy_p_m_interceptor.tscn": {"name": "[REVIEW] Interceptor", "codex": "[REVIEW] A fast strike fighter the Vertarine Armada bought as decommissioned military stock and pressed straight back into service. It fights in diving squadrons, each pass seeding a trail of slow drifting missiles to litter the space behind it. No great threat one at a time — but the Armada never bought them one at a time, and never flies them that way."},
	"res://scenes/enemies/core/enemy_core_m_minelayer.tscn": {"name": "ML-72 Minelayer", "codex": "A lumbering converted hauler armed with a large bay of mines and a rear ramp that can release them. Slow, unarmed, and prone to violently exploding when shot, these are support craft that should ideally never see combat."},
	"res://scenes/enemies/factions/privateer/enemy_p_m_cannon.tscn": {"name": "[REVIEW] Spectre", "codex": "[REVIEW] A privateer artillery platform: a heavy twin-barrel gun bolted onto whatever surplus hull could absorb the recoil. It holds position and lobs slow, heavy shells straight down the field, alternating barrels so one is always loading while the other fires. Easy to ignore right up until a shell connects — which is the mistake the Armada counts on."},
	"res://scenes/enemies/factions/privateer/enemy_p_m_pulse.tscn": {"name": "[REVIEW] Viper", "codex": "[REVIEW] A deep-holding gunner running cheap open-market plasma tech on a stolen airframe, the sort of parts-bin build the Vertarine Armada throws together in quantity. Its casters fling aimed bolts that weave as they fall, less from any real fire-control than from the loose tolerances of the salvaged emitters. Sloppy and unreliable, and made far too cheaply for the Armada to care."},
	"res://scenes/enemies/core/enemy_core_s_jet.tscn": {"name": "XF-101 Voodoo", "codex": "A light, fast experimental fighter build for speed and maneuverability over all else."},
	"res://scenes/enemies/factions/privateer/enemy_p_m_wing.tscn": {"name": "Wing", "codex": "[REVIEW] A broad-winged privateer strike craft hung with more missile rails than its frame was ever rated to carry. It sweeps across the field emptying them in a wide, unaimed spread meant to blanket ground rather than strike any one target. Pure Vertarine Armada doctrine — trade marksmanship for saturation and make up the accuracy in sheer weight of ordnance."},
	"res://scenes/enemies/core/enemy_core_s_caltrop.tscn": {"name": "B/A-56 Caltrop", "codex": "A Bomber-Attack craft with a unique rear-firing suspension cannon that fires entangled shots that drift through the void, waiting for something to hit them. These hulls are swift and agile for their bulk, and often leave trails of shots in the path of larger craft that can't turn out of the way swiftly."},
	"res://scenes/enemies/core/enemy_core_s_cobra.tscn": {"name": "CF/A-16D Cobra", "codex": "A workhorse fighter fielded by numerous miitaries across the stars. It is relatively sturdy, and its broad wings allow it to mount nearly any weapon system built. It comes with a pair of heavy wing-mounted cannons."},
	"res://scenes/enemies/factions/privateer/enemy_core_s_falchion.tscn": {"name": "[REVIEW] Falchion", "codex": "[REVIEW] A light, unarmed skirmisher run in bulk by fleets that value bodies over guns. It carries no weapon at all, weaving and sliding through the field purely to crowd it and pull fire off the hulls that matter. Its adaptive livery repaints itself in the colors of whatever flag musters it that run — a cheap, flag-agnostic hull built to be bought by anyone and mourned by none."},
	"res://scenes/enemies/factions/privateer/enemy_p_m_rocket.tscn": {"name": "[REVIEW] Rocket", "codex": "[REVIEW] A slow privateer gunship built around a fixed rocket rack, drifting into position and emptying salvo after salvo down its firing line while its hull guns rake anything nearer. It is meant to anchor a position and make the ground in front of it costly to cross, not to chase or maneuver. The Armada plants them like fenceposts and lets the rockets settle the argument."},
	"res://scenes/enemies/factions/supremacy/enemy_frigate.tscn": {"name": "[REVIEW] Tyrant", "codex": "[REVIEW] A Crimson Supremacy line frigate — slow, heavily armored, and built to fight with its broadside rather than its nose. It wheels ponderously to bring a full bank of guns to bear, then walks that fire across the field in a rolling barrage from whichever flank faces its target. No speed and no finesse, only enough armor and enough guns to grind down anything that can't out-position it."},
	"res://scenes/enemies/factions/supremacy/enemy_s_s_bully.tscn": {"name": "[REVIEW] Bully", "codex": "[REVIEW] A stocky Crimson Supremacy brawler that shoulders into a lane and dares you to move it. More attitude than armament, but it holds ground the Supremacy wants held."},
	"res://scenes/enemies/factions/supremacy/enemy_s_s_abductor.tscn": {"name": "[REVIEW] Abductor", "codex": "[REVIEW] A light Supremacy hull rigged with a gravity emitter that grabs at passing pilots and drags them off their line. Fragile, but a nuisance that pulls you into worse trouble."},
	"res://scenes/enemies/factions/supremacy/enemy_s_m_ravager.tscn": {"name": "[REVIEW] Ravager", "codex": "[REVIEW] A rangy Crimson Supremacy gunship, all length and guns, that bulls down the field trading fire the whole way. Built to punish anything caught in its lane."},
	"res://scenes/enemies/factions/supremacy/enemy_s_m_ruiner.tscn": {"name": "[REVIEW] Ruiner", "codex": "[REVIEW] A heavy Supremacy strike hull that commits to a target and does not relent. Slower than it looks, but what it points at, it means to ruin."},
	"res://scenes/enemies/factions/supremacy/enemy_s_m_scorcher.tscn": {"name": "[REVIEW] Scorcher", "codex": "[REVIEW] A Crimson Supremacy burner-hull that rakes a wide swath of the field with sustained fire, trading precision for coverage. Keep moving and don't let it settle its aim."},
	"res://scenes/enemies/factions/supremacy/enemy_s_m_plasma.tscn": {"name": "Scourge", "codex": "A medium gunship built with a wide-bore plasma spitter that unleashes shots of shaped plasma at victims. What they lack in speed and agility they make up for in damage potential, as the heavy shots are hard to avoid and especially effective against shields."},
	"res://scenes/enemies/factions/supremacy/enemy_s_m_push.tscn": {"name": "Overseer Frigate", "codex": "A tough frigate built with a pair of armored dome turrets firing powerful cannon shots at any ship foolish enough to get within range. Powerufl engines allow it to move swiftly, closing on prey, or maneuvering to advantageous positions with shocking speed."},
	"res://scenes/enemies/factions/supremacy/enemy_s_s_hotrod.tscn": {"name": "Lash", "codex": "A stripped-down racing frame fitted for combat, what it lacks in armor and firepower it makes up for in sheer speed and rate of fire. Crimson Supremacy outriders fly them to run prey down and herd it toward the heavier guns."},
	"res://scenes/enemies/factions/supremacy/enemy_s_s_rush.tscn": {"name": "Mauler", "codex": "An aggressive close-range brawler that charges straight in, firing short, snapping bursts from twin muzzles. It would sooner be in your face than across the field — typical of the Supremacy's contempt for caution."},
	"res://scenes/enemies/factions/zealot/enemy_beam_shooter.tscn": {"name": "Lantern", "codex": "A beam-wielding ship built as a testbed for the deadly plasma beam program the Evantians embarked upon some time ago. It is powered by numerous internal firecores and has extensive inertial damping tech and control thrusters that allow it to rake the dark with a purifying beam of fire that obliterates anything in its path."},
	"res://scenes/enemies/factions/zealot/enemy_beamer_lock.tscn": {"name": "Arbiter", "codex": "The Evantians carried out many experiments with plasma-beam technology, and the Arbiter is one result. It utilizes powerful gyroscopic mechanisms to rotate itself into firing position, then uses gravity locks to hold itself in place to fire. The plasma beam generated by this weapons platform is devastating, and best avoided."},
	"res://scenes/enemies/factions/zealot/enemy_beamer_tracker.tscn": {"name": "Inquisitor", "codex": "Agile, and accurate, these hand-built vessels are equipped with powerful beam projectors and multiple thruster arrays that allow it to quickly pivot and direct its beam of purifying plasma on its victims. It's bulk does mean it rotates slowly enough to outmaneuver, which is good, because only fools take on these vessels head-on."},
	"res://scenes/enemies/factions/zealot/enemy_burner.tscn": {"name": "Pyre", "codex": "Pyres are always dispatched in pairs, stringing a searing curtain of firecore-powered energy between them. The Evantians believe that to pass between two Pyres is to be cleansed, and these vessels rarely give victims the choice to partake in purification or now."},
	"res://scenes/enemies/factions/zealot/enemy_z_m_helix.tscn": {"name": "Helix Frigate", "codex": "The Helix-class frigate is built and flown by the Evantians primarily for its appearance, but the top-mounted plasma cannon is capable of firing precise, powerful shots if it ever needs to fight."},
	"res://scenes/enemies/factions/zealot/enemy_z_l_crusader.tscn": {"name": "[REVIEW] Crusader", "codex": "[REVIEW] A towering Evantian warship built to hold the front of a Theocracy advance and yield no ground. Four traversing turrets and a pair of fixed hull cannons keep a consecrated volley in the air on every approach, fed by the full bank of firecores its overbuilt frame is raised around. When that frame finally fails the cores tear loose and scatter across the void — loose fire the Evantians count as the ship's last sacrament."},
	"res://scenes/enemies/factions/zealot/enemy_z_s_bloom.tscn": {"name": "Firecore Bloom", "codex": "The bloom is a semi-stationary plasma generator that creates concentric rings of plasma charges for area denial. When destroyed, the cohesion fields break down, releasing balls of plasma in all directions."},
	"res://scenes/enemies/factions/zealot/enemy_z_s_manta.tscn": {"name": "Disciple", "codex": "Slow moving and lightly armed, the Disciple is among one of the more common craft utilized by the Evantian fleets, often put to work as escorts in large numbers, their presence is meant to distract and any kills they score are a bonus."},
	"res://scenes/enemies/factions/zealot/enemy_z_s_acolyte.tscn": {"name": "Acolyte", "codex": "The Acolyte is neither fast nor particularly agile, but it does bring two wide-angle plasma dispersing guns to bear, filling the void with shots meant to hit anything caught in the way."},
	"res://scenes/enemies/factions/zealot/enemy_z_s_drifter.tscn": {"name": "Drifter", "codex": "An unarmed scout, the Drifter is rarely a danger to anyone on its own, but is always a precursor to the arrival of greater numbers of Evantian forces. The pilots are selected from the most disposable of the ranks, given little training, and often used as screening waves to protect more valuable craft."},
	"res://scenes/enemies/factions/zealot/enemy_z_s_shiv.tscn": {"name": "Shiv", "codex": "Shiv-class interceptors lack weapons of any kind, and instead rely on sharpened hulls reinforced for impact. Shivs are piloted by the elderly, prisoners, and zealots who have agreed to deliver the light of the Firecore to deserving heathen foes."},
	"res://scenes/enemies/factions/zealot/enemy_z_s_sword.tscn": {"name": "Sword Frigate", "codex": "The Sword-class Frigate is built and fielded exclusively by the Evantian Theocracy, and is a fast workhorse combat vessel. It features multiple omni-directional plasma casters capable of rapidly firing salvos at enemies."},
	"res://scenes/enemies/factions/zealot/enemy_z_s_crook.tscn": {"name": "Crook", "codex": "The Crook is a modestly fast fighter with a rapid-fire plasma cannon. What it lacks in armor and maneuverability it makes up for with rate of fire."},
	"res://scenes/enemies/factions/zealot/enemy_z_s_pilgrim.tscn": {"name": "Pilgrim", "codex": "The Pilgrim isn't fast, maneuverable, or terribly well armored, but it does feature dual heavy plasma cannons capable of firing rapidly at any foes caught in their sights."},
	"res://scenes/enemies/factions/zealot/enemy_z_s_censer.tscn": {"name": "Censer Frigate", "codex": "The Censer-class frigate is not especially fast, but it is well armored and features two nose-mounted heavy wave projectors that create walls of burning plasma."},
	"res://scenes/enemies/factions/zealot/enemy_z_s_cross.tscn": {"name": "Cross Gunship", "codex": "A fast-moving gunboat with omni-directional thrust capacity and two front-mounted laser cannons for rapid, precise attack. While speedy, these vessels are not especially resilient and tend to explode violently when destroyed."},
	"res://scenes/enemies/factions/zealot/enemy_z_s_rebuker.tscn": {"name": "Rebuker", "codex": "The Rebuker is a slow moving but maneuverable attack vessel that is heavily armed, wielding two forward facing plasma cannons. What it lacks in speed it makes up for in power and capability to harrass combatants with direct, accurate fire."},
	"res://scenes/enemies/factions/zealot/enemy_z_s_spear.tscn": {"name": "Spear Frigate", "codex": "The high-speed Spear-Class Frigate trades conventional plasma cannons for a central firecore-powered plasma generator that can fire coherent beams. It is fast, and agile, with powerful thruster engnines allowing it to quickly reverse and pivot in space to get its beam on target quickly."},
	"res://scenes/enemies/factions/zealot/boss_z_l_shepherd.tscn": {"name": "The Shepherd", "codex": "An Evantian capital-ship that herds its flock to slaughter. Its four turrets carry the fight, delivering salvos of burning plasma. It also carries massive missile bays capable of dispatching dozens of warheads in rapid succession for area denial or stand-off fleet engagement. The Shepherd is never seen alone, and any attempt to breach its hull will require a Starblaster to engage with its escorting flock first."},
	"res://scenes/enemies/factions/zealot/firecore_core.tscn": {"name": "Firecore", "codex": "The sacred heart of every Evantian hull, this unstable micro-star serves as the power source for every every system, and the point of worship for its crew. The Theocracy worships is as a source power and salvation, believing that one day all the firecores will rupture, and consume the worthy in great waves of fire and light."},
	"res://scenes/enemies/factions/zealot/firecore_hazard.tscn": {"name": "Loose Firecore", "codex": "A firecore shaken loose from a dying Evantian ship, rather than detonating it drifts through space, a micro-star burning brightly in the void"},
	"res://scenes/enemies/tether_mine.tscn": {"name": "VM-T4 Tether Mine", "codex": "Void Munitions T4 Tether Mine in its capital-launched configuration — flung into the field by flagships to pin a pilot in place. Dormant until you stray near, then it lashes out a grappling beam and reels you in. Kill it to cut the line."},
}


# Display name for a scene path. Falls back to a derived name (file stem, sans
# "enemy_", underscores -> spaces) for any scene not in the table.
static func display_name(scene_path: String) -> String:
	var e: Variant = STRINGS.get(scene_path, null)
	if e != null and str(e.get("name", "")) != "":
		return str(e["name"])
	return _derive(scene_path)


# Codex flavor text for a scene path ("TBD" default for unlisted / unfilled).
static func codex_entry(scene_path: String) -> String:
	var e: Variant = STRINGS.get(scene_path, null)
	if e != null:
		return str(e.get("codex", "TBD"))
	return "TBD"


static func _derive(scene_path: String) -> String:
	var stem: String = scene_path.get_file().get_basename()
	if stem.begins_with("enemy_"):
		stem = stem.substr(6)
	return stem.replace("_", " ")
