extends CanvasLayer

# Pause overlay. Listens for Esc; on input pauses the tree, dims screen, shows
# the menu. Resume / Options / Main Menu (saves) / Quit.

const VolumeSliderScene = preload("res://scenes/volume_slider.tscn")
const SceneTransition = preload("res://scripts/scene_transition.gd")
const UiTheme = preload("res://scripts/ui/ui_theme.gd")

@onready var dim: ColorRect = $Dim
@onready var resume_btn: Button = $Center/VBox/ResumeBtn
@onready var menu_btn: Button = $Center/VBox/MenuBtn
@onready var quit_btn: Button = $Center/VBox/QuitBtn
@onready var status_label: Label = $Center/VBox/StatusLabel
@onready var vbox: VBoxContainer = $Center/VBox

var _paused: bool = false

func _ready() -> void:
	process_mode = Node.PROCESS_MODE_ALWAYS  # keep responding while paused
	visible = false
	# Dim deeper so the menu reads against the running game underneath.
	# Same look as the main menu's centered panel.
	if dim:
		dim.color = Color(0, 0, 0, 0.7)
	# Apply unified theme to the in-game pause menu's chrome.
	for b in [resume_btn, menu_btn, quit_btn]:
		b.custom_minimum_size = Vector2(160, 22)
		UiTheme.style_button(b, true)
	UiTheme.style_label(status_label, UiTheme.LabelKind.BODY)
	# The "PAUSED" header lives at $Center/VBox/@Label@20636 — find it by
	# index since the autogenerated node name isn't stable. It's the first
	# Label child of the VBox.
	for child in vbox.get_children():
		if child is Label and child.text == "PAUSED":
			# Use HEADER (16px) instead of TITLE (28px) to fit 480x270 viewport.
			UiTheme.style_label(child, UiTheme.LabelKind.HEADER)
			child.horizontal_alignment = HORIZONTAL_ALIGNMENT_CENTER
			break
	resume_btn.pressed.connect(_resume)
	menu_btn.pressed.connect(_to_menu)
	quit_btn.pressed.connect(_quit)
	_install_options_button()


func _install_options_button() -> void:
	# Replaces the inline volume slider (Roman, 2026-05-16): pause menu now
	# routes through the shared Options overlay so settings are consistent
	# with the main-menu surface.
	var btn := Button.new()
	btn.text = "Options"
	btn.custom_minimum_size = Vector2(160, 22)
	UiTheme.style_button(btn, true)
	btn.pressed.connect(_open_options)
	vbox.add_child(btn)
	vbox.move_child(btn, menu_btn.get_index())


func _open_options() -> void:
	var OptionsOverlay = load("res://scripts/ui/options_overlay.gd")
	OptionsOverlay.open(self)

func _unhandled_input(event: InputEvent) -> void:
	if event is InputEventKey and event.pressed and event.keycode == KEY_ESCAPE:
		_toggle()

func _toggle() -> void:
	_paused = not _paused
	visible = _paused
	get_tree().paused = _paused
	# Freeze the music intensity walk while paused so a long pause doesn't
	# escalate or de-escalate the track (Roman, 2026-05-16).
	if has_node("/root/Music"):
		get_node("/root/Music").set_walk_frozen(_paused)
	if _paused:
		_refresh_status()

func _refresh_status() -> void:
	if has_node("/root/Run"):
		var run = get_node("/root/Run")
		status_label.text = "Hull: %d/%d   Shield: %d/%d   Bounty: %d" % [
			run.current_hull, run.max_hull, run.current_shield, run.max_shield, run.bounty
		]
	else:
		status_label.text = ""

func _resume() -> void:
	_toggle()

func _to_menu() -> void:
	# Pause menu lives in combat — bailing here scraps the current level's
	# progress (waves cleared, bounty earned mid-level). The saved sector
	# is still safe (autosaved on last map entry), so the run resumes from
	# that node, not this fight. Warn first so this isn't a one-click ragequit.
	_show_menu_warning()


func _show_menu_warning() -> void:
	var layer := CanvasLayer.new()
	layer.layer = 95
	layer.process_mode = Node.PROCESS_MODE_ALWAYS
	var dim := ColorRect.new()
	dim.color = Color(0, 0, 0, 0.75)
	dim.set_anchors_and_offsets_preset(Control.PRESET_FULL_RECT)
	dim.mouse_filter = Control.MOUSE_FILTER_STOP
	layer.add_child(dim)
	var center := CenterContainer.new()
	center.set_anchors_and_offsets_preset(Control.PRESET_FULL_RECT)
	layer.add_child(center)
	var panel := PanelContainer.new()
	var sb := StyleBoxFlat.new()
	sb.bg_color = UiTheme.COLOR_PANEL_BG
	sb.border_color = UiTheme.COLOR_ACCENT_DIM
	sb.border_width_left = 2; sb.border_width_top = 2
	sb.border_width_right = 2; sb.border_width_bottom = 2
	sb.content_margin_left = 12; sb.content_margin_right = 12
	sb.content_margin_top = 10; sb.content_margin_bottom = 10
	panel.add_theme_stylebox_override("panel", sb)
	center.add_child(panel)
	var v := VBoxContainer.new()
	v.add_theme_constant_override("separation", 8)
	v.custom_minimum_size = Vector2(240, 0)
	panel.add_child(v)
	var head := Label.new()
	head.text = "Return to Main Menu?"
	head.horizontal_alignment = HORIZONTAL_ALIGNMENT_CENTER
	UiTheme.style_label(head, UiTheme.LabelKind.HEADER)
	v.add_child(head)
	var body := Label.new()
	body.text = "Leaving this level will scrap your progress in it.\nYour patrol resumes from the sector map."
	body.horizontal_alignment = HORIZONTAL_ALIGNMENT_CENTER
	body.autowrap_mode = TextServer.AUTOWRAP_WORD_SMART
	body.custom_minimum_size = Vector2(220, 0)
	UiTheme.style_label(body, UiTheme.LabelKind.BODY)
	v.add_child(body)
	var btn_row := HBoxContainer.new()
	btn_row.alignment = BoxContainer.ALIGNMENT_CENTER
	btn_row.add_theme_constant_override("separation", 12)
	v.add_child(btn_row)
	var cancel := Button.new()
	cancel.text = "Cancel"
	cancel.custom_minimum_size = Vector2(96, 22)
	UiTheme.style_button(cancel, true)
	cancel.pressed.connect(func(): layer.queue_free())
	btn_row.add_child(cancel)
	var confirm := Button.new()
	confirm.text = "Leave"
	confirm.custom_minimum_size = Vector2(96, 22)
	UiTheme.style_button(confirm)
	confirm.pressed.connect(func():
		get_tree().paused = false
		SceneTransition.change_scene(get_tree(), "res://scenes/main_menu.tscn")
	)
	btn_row.add_child(confirm)
	add_child(layer)

func _quit() -> void:
	get_tree().paused = false
	get_tree().quit()
